### ISSUE TITLE
Implement registration form with fields for firstname, lastname, username, and password.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Client#1]

**Comment by Modemacher** [comment]
Did that on 6.4.24

**Comment by Modemacher** [comment]
9bb124194348185448b5a00bbe4a204e881e7ee0 a8dbbd607639ae2960b03a7bb75724786e22bcd7 5d175410523721c5129819a3cda526aa7c5c87b9 686136e2ee2f941339b6e209093ab7144a9ec019 ccc09bb6d3f274024bb8a7912cdb1bfd3fdcfe23 80086f45532924298142bc14ddfecb85ec6af741 447c8edc07a27d36158cee34bd717d0655237018 5c01ebee1842b393cfd0bf96c3ff4c94661633e7 63ff9d11c09e7a95128492b870e19da7b486e022 dd90671962449f95f838d3662f2d922cd926bc3a ecf3c944eb1b3dfff64edcf1c406e1e31173fa24 f0d215e7ed22a826c9a1f76d6a63df3f0578ea36 0ba5cc064659963ab08dad967990761a2aeb0fb1 3d67e555a2a9b2bb45949c40925d57648a717ba3 86094d1a92c24ed4287ab77e347a0426beaf356d 99b05b653ae78cb616044995f2aecc2dedc3df1c d9c9c42d0ff16e189dedf1495f59fa06683b299e 86570751d7dd4d120f611499889db2c500bb43e0 0560422092098b83935f04a685e00350199aae6d 503bb5464bfee6e5149f020697bc940512eeec87 28bf310cd8782940d5868302262ee77dff29d53e

**Comment by Modemacher** [comment]
I did so many design changes and this and that on that field those things are not possible to but my time on.
