### ISSUE TITLE
Implement functionality to allow the event host to edit event details.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Client#11]

**Comment by noystad** [comment]
Rejected, Remove Event and readd on errors.

**Comment by noystad** [comment]
Rejected, remove Event on errors and recreate.

**Comment by Modemacher** [comment]
f33dd664ba5e0b6023aa6f9172606973bbd486d9 b2903187242e74d195c1380a119346dd903b0440 10757a51cd5145eee2c967972273b7aa1789df42 ce157efabadd4fbb741c18d6de468a0f6723bb32 ac958a3f94b5889d898a03336dc63841eeed97ab 8f9b0806bb3337535ff4c30dc617d9844bcb2592 a7da664702ae5434b37dc7ac6d1e92d3b3aede6e
