### ISSUE TITLE
Implement functionality to mark the ingredient as assigned to the respective group member once claimed.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Client#22]

**Comment by Modemacher** [comment]
mike did 90% of that

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Server/issues/12

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/65c7654e147bd8abe84f19707e13102686a82b55
https://github.com/sopra-fs24-group-10/Client/commit/7ad96f3c49970c200ccbb8ffb79348fac4c98de3
https://github.com/sopra-fs24-group-10/Client/commit/0c0d2af7a08bc0b1c019e37dc2e799041aaf7d19
https://github.com/sopra-fs24-group-10/Client/commit/7f38f7a147a64098f9e396ee99d3691b4b0a4a2b#diff-f87349bcd0c79b4dfa6b804b9befaa899435aa8076472cc01100cb9e6cd9c592
