### ISSUE TITLE
Create functionality to update assignments directly from the interface, including re-assigning and unassigning ingredients.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Client#25]

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/7f38f7a147a64098f9e396ee99d3691b4b0a4a2b#diff-f87349bcd0c79b4dfa6b804b9befaa899435aa8076472cc01100cb9e6cd9c592

together with timon 
https://github.com/sopra-fs24-group-10/Client/commit/f4ba0708ccb51a4700d0980a90c4cda971feddb0#diff-dfff4a2e4fe14e5bf29b4d19c2e58d5cbb6d37db891aa21f2b40d17c63eb2a87

**Comment by tirudouzh** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/f4ba0708ccb51a4700d0980a90c4cda971feddb0#diff-dfff4a2e4fe14e5bf29b4d19c2e58d5cbb6d37db891aa21f2b40d17c63eb2a87
