### ISSUE TITLE
Integrate the rating display on the favourite and or event page, showing the average rating and possibly the number of ratings.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Client#33]

**Comment by mikfre1** [comment]
0bb027c78eeab305f4e47aa430e310a326605fe8

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/a263e0314dfd76e84aaf38c73e2bfcaf28ecf514
https://github.com/sopra-fs24-group-10/Client/commit/17d2bc2e447d088a403eab87feb1e3aa3da4fa59
https://github.com/sopra-fs24-group-10/Client/commit/f5f3e6c15b721c037e5e2bd235a3317fbf4f28d0
