### ISSUE TITLE
Implement login form with fields for username and password.

### ISSUE THREAD

**Issue by noystad** [sopra-fs24-group-10/Client#4]

**Comment by Modemacher** [comment]
I created the static design and so minor logic creations from MUI for the login page. The login page is a good signpost for future pages. 

You can now login and write a password (as far without logic) 


#4

**Comment by Modemacher** [comment]
done

**Comment by Modemacher** [comment]
9bb124194348185448b5a00bbe4a204e881e7ee0
5d175410523721c5129819a3cda526aa7c5c87b9
ccc09bb6d3f274024bb8a7912cdb1bfd3fdcfe23
