### ISSUE TITLE
Image Upload UI: Create an "Upload Picture" button or area in the profile settings.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Client#50]

**Comment by Modemacher** [comment]
6111274eed93ea8e597904a4952a08f9f1f02365 0d1141812292004700e2c3ec3f68fdf70fca2c89 f8f862c7f976252880fbfad43f46e1a3732f5150 86094d1a92c24ed4287ab77e347a0426beaf356d

c4baac1218a6192aa034b7598c794ac4170c3ec4 756a95492bbd8bb9b14018fd5b43560954f509cb 4c5219995121223d268411a0fc70499e5788c74e d2912bd48510fca720bf4287cb5184d2afdcdd8a fedd45fb18f972e1f6744e7b4e4cea73bd1c3514
