### ISSUE TITLE
Display Profile Picture: Code the display of the stored profile picture in the appropriate profile section.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Client#51]

**Comment by Modemacher** [comment]
c4baac1218a6192aa034b7598c794ac4170c3ec4 756a95492bbd8bb9b14018fd5b43560954f509cb 4c5219995121223d268411a0fc70499e5788c74e d2912bd48510fca720bf4287cb5184d2afdcdd8a fedd45fb18f972e1f6744e7b4e4cea73bd1c3514
