### ISSUE TITLE
Create a dialog to confirm the deletion.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Client#53]

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/8edcb30d0a2b963157f3783bc468533d917431a7

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/0bf7f0f7929ce563ccda031e18db2f47576eff50
https://github.com/sopra-fs24-group-10/Client/commit/f73d3fe5aa108fd26ab28bb584563416eda82631#diff-6906f3ef4f65e320ed93f865135626300b972186f090c5db5285a0be728e84ea
