### ISSUE TITLE
Add a button to leave the event within the event participant page.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Client#54]

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/c1db7b7316efe882e3e7e0607b8b0cf579a3f01e

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/71f890ffd98a72ae212477a27e3250730da57e6b
https://github.com/sopra-fs24-group-10/Client/commit/4eabb7ccc641c7a5c63c34a036a2a2f731f5a701
