### ISSUE TITLE
Create a dialog to confirm the exit of the partitcipant in the event.

### ISSUE THREAD

**Issue by tirudouzh** [sopra-fs24-group-10/Client#55]

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/c1db7b7316efe882e3e7e0607b8b0cf579a3f01e

**Comment by mikfre1** [comment]
https://github.com/sopra-fs24-group-10/Client/commit/4eabb7ccc641c7a5c63c34a036a2a2f731f5a701
https://github.com/sopra-fs24-group-10/Client/commit/0f5676bd07aa2423a448d0977945ca2bfe9b553c
